apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ip.localhost.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: ip-lookup
                port:
                  number: 8087
    - host: excalidraw.localhost.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: excalidraw
                port:
                  number: 8086
    - host: stage.mattcarrier.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mattcarrier
                port:
                  number: 8085
    - host: mattcarrier.localhost.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mattcarrier
                port:
                  number: 8085
